apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # my-user  
  db_user: "my-user"
  # my-pass
  db_pwd: "my-pass"
  # my-app-db
  db_name: "my-app-db"
  # secret-root-pass
  db_root_pwd: "secret-root-pass"
